version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: maps-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=maps_db
    restart: unless-stopped

  maps-api:
    build: .
    ports:
      - "8000:8000"
    #volumes:
    #  - ./maps_data.json:/app/maps_data.json
    #  - ./image_cache:/app/image_cache
    environment:
      - PYTHONUNBUFFERED=1
      - STORAGE_TYPE=mongodb
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/maps_db?authSource=admin
      - MONGODB_DATABASE=maps_db
      - API_TYPE=fastapi
    depends_on:
      - mongodb
    restart: unless-stopped

  # Optional: Add nginx for production
  #nginx:
  #  image: nginx:alpine
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
  #  depends_on:
  #    - maps-api
  #  profiles:
  #    - production

volumes:
  mongodb_data: